### ISSUE TITLE
What happened to this repository?

### ISSUE THREAD

**Issue by goodhoko** [whosonfirst-data/whosonfirst-data-admin-at#13]
It looks like contents of this repository were purged and replaced by something completely different?
1) This repository is named `whosonfirst-data-admin-at` but it's root README has a heading of `whosonfirst-data-venue-at`
2) Much of the data that were formerly here are now gone. For example all regions and e.g. https://spelunker.whosonfirst.org/id/85681649/ to give a concrete example.
3) There are only two commits by @thisisaaronland. Both from 3 days ago.

Is this intentional? If so, where can I find the data that were formerly in this repo?

**Comment by straup** [comment]
This was caused by an error on my part. The data will be restored shortly (like a few hours, maybe EOD). Apologies for the confusion.

**Comment by goodhoko** [comment]
Thanks. Will close this once resolved.

**Comment by stepps00** [comment]
Thanks for flagging, @goodhoko.

We just pushed a local copy of this repo to `master`, which should fix this issue. Feel free to close this out if the changes are as expected.

**Comment by goodhoko** [comment]
LGTM. Thanks a lot for fast response. <3

Closing.
